tls:
  certificates:
    - certFile: /letsencrypt/live/ineiah.fr/fullchain.pem
      keyFile: /letsencrypt/live/ineiah.fr/privkey.pem
   
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
       - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
       - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
       - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
       - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
       - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
       - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
       - "ECDHE-ECDSA-AES256-GCM-SHA384"
       - "ECDHE-RSA-AES256-GCM-SHA384"
       - "ECDHE-ECDSA-CHACHA20-POLY1305"
       - "ECDHE-RSA-CHACHA20-POLY1305"

