# https://www.spad.uk/posts/practical-configuration-of-traefik-as-a-reverse-proxy-for-docker/

global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true # Set to false in production

log:
  level: ERROR
  filePath: /var/log/traefik.log
  
accessLog:
  filePath: /var/log/traefik_access.log

entryPoints:
  web:
    address: :80      
    # Permanent redirect to port
    # HTTPS and prevent any HTTP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  traefik:
    address: :8080

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: myprosite_network
  file:
    directory: etc/traefik/dynamic
    watch: true

metrics:
  prometheus: {}

tracing: {}

certificatesResolvers:
  staging:
    acme:
      email: contact@ineiah.fr
      storage: /letsencrypt/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: contact@ineiah.fr
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

experimental:
  plugins:
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.3"
